In [1]:
# # Pytorch MNIST digits example from https://machinelearningmastery.com/handwritten-digit-recognition-with-lenet5-model-in-pytorch/
# # THIS IS ME PLAYING WITH a relatively large MLP for fun
# # SEEMS TO WORK WELL > 98% ACCURACY!!!


# # Imports
import torch # Main PyTorch module
import torch.nn as nn # Neural Network module
import torch.optim as optim  # Optimization module
import torchvision # Computer Vision module
import matplotlib.pyplot as plt
from tqdm import tqdm
import sys
import numpy as np
import time
import math
import nnfs



/Users/user/miniconda3/envs/mlproj/lib/python3.12/site-packages/torchvision/io/image.py:14: UserWarning: Failed to load image Python extension: 'dlopen(/Users/user/miniconda3/envs/mlproj/lib/python3.12/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: <367D4265-B20F-34BD-94EB-4F3EE47C385B> /Users/user/miniconda3/envs/mlproj/lib/python3.12/site-packages/torchvision/image.so
  Reason: tried: '/Users/user/miniconda3/envs/mlproj/lib/python3.12/site-packages/torchvision/../../../libjpeg.9.dylib' (no such file), '/Users/user/miniconda3/envs/mlproj/lib/python3.12/site-packages/torchvision/../../../libjpeg.9.dylib' (no such file), '/Users/user/miniconda3/envs/mlproj/lib/python3.12/lib-dynload/../../libjpeg.9.dylib' (no such file), '/Users/user/miniconda3/envs/mlproj/bin/../lib/libjpeg.9.dylib' (no such file)'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be someth

In [2]:
## Implementing softmax now in a neural networks

## Softmask function is exp(value) / sum of all exp(values) 

layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

# Subtract largest value prior to exponentiation to improve numerical stability and avoid overflow. The output does not change.

exp_values = np.exp(layer_outputs - np.max(layer_outputs, axis=1, keepdims=True))

norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True) ## Matrix of exact same dimension of layer_outputs

print("Normalised values = ", norm_values)
# print("Sum of normalised values = ", np.sum(norm_values), " (should be 1.0)")



Normalised values =  [[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [3]:
from nnfs.datasets import spiral_data
np.random.seed(0) ## Set random seed for reproducibility

nnfs.init() ## Initialize nnfs (sets default data type to float32 etc.)

## Create Layer class 
class Layer_Dense: 
    def __init__(self, n_inputs, n_neurons): ## n_inputs = number of inputs to the layer, n_neurons = number of neurons in the layer
        ## Initialize weights and biases
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) ## Random weights with small values. This is useful for forward pass and we do not need to transpose weights here.
        self.biases = np.zeros((1, n_neurons)) ## Biases should be initialized to zero values

    def forward(self, inputs):
        ## Forward pass
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        ## Apply ReLU activation function
        self.output = np.maximum(0, inputs) ## Element-wise maximum operation

class softmax_Activation:
    def forward(self, inputs):
        ## Apply Softmax activation function
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True)) ## Subtract max for numerical stability
        probabilities= exp_values / np.sum(exp_values, axis=1, keepdims=True) ## Normalization step
        self.output = probabilities


## Create first layer
X, y = spiral_data(samples = 100, classes =3) ## Create dataset with 3 classes
dense1 = Layer_Dense(2,3) ## Create first dense layer with 2 inputs and 3 neurons
# Create activation function
activation1 = Activation_ReLU() ## Create ReLU activation function object


dense2 = Layer_Dense(3,3) ## Create second dense layer with 3 inputs (from previous layer) and 3 neurons
activation2 = softmax_Activation() ## Create Softmax activation function object

dense1.forward(X) ## Forward pass through first layer
dense2.forward(dense1.output) ## Forward pass through second layer

activation1.forward(dense1.output) ## Apply ReLU activation function to output of first layer
activation2.forward(dense2.output) ## Apply Softmax activation function to output of second layer

print("First layer output after ReLU activation = \n", activation1.output[:5]) ## Print output of first layer after ReLU activation
print("\n")
print("Second layer output after Softmax activation = \n", activation2.output[:5]) ## Print output of second layer after Softmax activation


First layer output after ReLU activation = 
 [[0.         0.         0.        ]
 [0.         0.00113954 0.        ]
 [0.         0.00317292 0.        ]
 [0.         0.00526663 0.        ]
 [0.         0.00714014 0.        ]]


Second layer output after Softmax activation = 
 [[0.33333334 0.33333334 0.33333334]
 [0.33334687 0.33334196 0.3333112 ]
 [0.3333612  0.3333536  0.33328524]
 [0.33336097 0.33335987 0.33327916]
 [0.33337367 0.3333704  0.33325592]]
