In [2]:
# # Pytorch MNIST digits example from https://machinelearningmastery.com/handwritten-digit-recognition-with-lenet5-model-in-pytorch/
# # THIS IS ME PLAYING WITH a relatively large MLP for fun
# # SEEMS TO WORK WELL > 98% ACCURACY!!!


# # Imports
import torch # Main PyTorch module
import torch.nn as nn # Neural Network module
import torch.optim as optim  # Optimization module
import torchvision # Computer Vision module
import matplotlib.pyplot as plt
from tqdm import tqdm
import sys
import numpy as np
import time

https://www.youtube.com/watch?v=lGLto9Xd7bU&list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3&index=2 - Reference 

In [14]:
## Convert the above to object oriented code

In [19]:

X = [[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[ -1.5,2.7,3.3,-0.8]] ## 3 sets of inputs data 

## Create Layer class 
class Layer_Dense: 
    def __init__(self, n_inputs, n_neurons): ## n_inputs = number of inputs to the layer, n_neurons = number of neurons in the layer
        ## Initialize weights and biases
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) ## Random weights with small values. This is useful for forward pass and we do not need to transpose weights here.
        self.biases = np.zeros((1, n_neurons)) ## Biases should be initialized to zero values

    def forward(self, inputs):
        ## Forward pass
        self.output = np.dot(inputs, self.weights) + self.biases



## Create first layer
layer1 = Layer_Dense(n_inputs=4, n_neurons=5) ## First layer with 4 inputs and 5 neurons
layer2 = Layer_Dense(n_inputs=5, n_neurons=2) ## Second layer with 5 inputs (from previous layer) and 2 neurons
## Forward pass through the layers
layer1.forward(X) ## Forward pass through first layer. We will now have layer1.output value
print("Layer 1 output = \n", layer1.output) ## Print output of first layer
layer2.forward(layer1.output) ## Forward pass through second layer. We will now have layer2.output value which is calculated from output of first layer
print("Layer 2 output = \n", layer2.output) ## Print output of second layer

Layer 1 output = 
 [[-0.25019707  0.29621499 -0.44316805  0.26722439 -0.07514709]
 [-0.0591695   0.61932802 -0.37870028  1.13393833 -0.65706718]
 [-0.19564971 -0.13415211 -0.14491714 -0.33268666 -0.06286878]]
Layer 2 output = 
 [[ 0.01619024  0.04631842]
 [-0.17965935  0.02002777]
 [ 0.04101197  0.05067731]]


## Activation function --> https://www.youtube.com/watch?v=gmjzbpSVY1A&list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3&index=5 

In [ ]:
# Why do we use activation functions?

# Ans. Activation functions introduce non-linearity into the neural network, allowing it to learn and model complex patterns in the data. 
# Without activation functions, a neural network would simply be a linear combination of its inputs, limiting its ability to capture intricate relationships. 
# Non-linear activation functions enable the network to approximate any continuous function, making it more powerful and capable of solving a wide range of tasks, such as image recognition, natural language processing, and more.
# Some common activation functions include ReLU (Rectified Linear Unit), Sigmoid, and Tanh.
# So with linear activation function you can only fit linear data but with non linear activation function you can fit complex non linear data also.

In [ ]:
## Step function or Heaviside step function as an activation function. 
# Activation function is applied to the output of the layer to introduce non-linearity i.e. it comes into play after the forward pass of the layer so when we have done inputs * weights + biases.
# Step function outputs 1 if input is greater than 0 else it outputs 0.
# This is a simple activation function and is not commonly used in practice but is useful for understanding the concept of activation functions.
# The output of the activation function is then passed to the next layer as input. 
# We need activation functions to introduce non-linearity in the model so that it can learn complex patterns in the data.


# Another activation function is the sigmoid function which outputs values between 0 and 1.
# It is defined as 1 / (1 + exp(-x)) where x is the input to the function.
# Sigmoid function is better than step function as it is differentiable and smooth and calculates loss better.
# Sigmoid has the problem of vanishing gradient for very high or very low values of input where the gradient becomes very small and the model stops learning.

# Another activation function is the Relu function.
# The rectified linear unit (ReLU) is another popular activation function. 
# It outputs the input directly if it is positive else it outputs 0. The formula is max(0, x). 
# It is computationally efficient and helps in reducing the likelihood of vanishing gradient problem because it does not saturate for positive values.
# ReLU is widely used in deep learning models and has been shown to work well in practice.

