In [2]:
# # Pytorch MNIST digits example from https://machinelearningmastery.com/handwritten-digit-recognition-with-lenet5-model-in-pytorch/
# # THIS IS ME PLAYING WITH a relatively large MLP for fun
# # SEEMS TO WORK WELL > 98% ACCURACY!!!


# # Imports
import torch # Main PyTorch module
import torch.nn as nn # Neural Network module
import torch.optim as optim  # Optimization module
import torchvision # Computer Vision module
import matplotlib.pyplot as plt
from tqdm import tqdm
import sys
import numpy as np
import time

https://www.youtube.com/watch?v=lGLto9Xd7bU&list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3&index=2 - Reference 

In [5]:
#### Model 3 neurons with 4 inputs with unique weights and biases

# some_value = -0.5
# weight = 0.7
# bias = 0.7

# print("Some value:", some_value*weight)
# print(some_value+bias) # Adding bias offsets the value

'''
inputs = [1,2,3,2.5] ## 4 inputs to the layer

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]] ## All weights in one list

biases = [2.0,3.0,0.5] ## All biases in one list

layer_outputs = [] ## Store outputs of each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 ## Reset neuron output
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight ## Weighted sum
    neuron_output += neuron_bias ## Add bias
    layer_outputs.append(neuron_output) ## Store output


print(layer_outputs) ## Print outputs of all neurons
'''
#### END Model 3 neurons with 4 inputs with unique weights and biases

Some value: -0.35
0.19999999999999996


'\ninputs = [1,2,3,2.5] ## 4 inputs to the layer\n\nweights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]] ## All weights in one list\n\nbiases = [2.0,3.0,0.5] ## All biases in one list\n\nlayer_outputs = [] ## Store outputs of each neuron\nfor neuron_weights, neuron_bias in zip(weights, biases):\n    neuron_output = 0 ## Reset neuron output\n    for n_input, weight in zip(inputs, neuron_weights):\n        neuron_output += n_input * weight ## Weighted sum\n    neuron_output += neuron_bias ## Add bias\n    layer_outputs.append(neuron_output) ## Store output\n\n\nprint(layer_outputs) ## Print outputs of all neurons\n'

In [ ]:
# Shape of the data is very important. PyTorch expects data in a specific shape which is different from other libraries like TensorFlow/Keras. 
# It is important to understand how to reshape data correctly. 

In [8]:
inputs = [1,2,3,2.5] ## 4 inputs to the layer

weights = [[0.2,0.8,-0.5,1.0]] ## All weights in one list

biases = 2 ## All biases in one list

output = np.dot(weights, inputs) + biases ## Using numpy for matrix multiplication and adding biases. We use weights first to get correct shape of output because numpy follows standard matrix multiplication rules.

print(output) ## Print outputs of all neurons

[4.8]


In [10]:
inputs = [1,2,3,2.5] ## 4 inputs to the single layer

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]] ## All weights in one list, the three sets of weights tells us that there are 3 neurons in this layer.

biases = [2.0,3.0,0.5] ## All biases in one list

layer_outputs = np.dot(weights, inputs) + biases ##  We use weights first to get correct shape of output because numpy follows standard matrix multiplication rules.

print(layer_outputs) ## Print outputs of all neurons

[4.8   1.21  2.385]


In [13]:
# Using batches of inputs

inputs = [[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[ -1.5,2.7,3.3,-0.8]] ## 3 sets of inputs (a batch of 3)

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]] ## All weights in one list, the three sets of weights tells us that there are 3 neurons in this layer.

biases = [2.0,3.0,0.5] ## All biases in one list

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases ##  We use weights first to get correct shape of output because numpy follows standard matrix multiplication rules. Transpose weights to align correctly.

print("Layer 1 out = ", layer_outputs) ## Print outputs of all neurons

weights2 = [[0.1, -0.14, 0.5], [-0.5, 0.12, -0.33], [-0.44, 0.73, -0.13]] ## Weights for the second layer

biases2 = [-1.0, 2.0, -0.5] ## Biases for the second layer

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2 ## Output of second layer, the output of the first layer is the input to the second layer.

print()
print("Layer 2 out = ", layer2_outputs) ## Print outputs of all neurons in layer 2


Layer 1 out =  [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]

Layer 2 out =  [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [14]:
## Convert the above to object oriented code

In [19]:

X = [[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[ -1.5,2.7,3.3,-0.8]] ## 3 sets of inputs data 

## Create Layer class 
class Layer_Dense: 
    def __init__(self, n_inputs, n_neurons): ## n_inputs = number of inputs to the layer, n_neurons = number of neurons in the layer
        ## Initialize weights and biases
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) ## Random weights with small values. This is useful for forward pass and we do not need to transpose weights here.
        self.biases = np.zeros((1, n_neurons)) ## Biases should be initialized to zero values

    def forward(self, inputs):
        ## Forward pass
        self.output = np.dot(inputs, self.weights) + self.biases



## Create first layer
layer1 = Layer_Dense(n_inputs=4, n_neurons=5) ## First layer with 4 inputs and 5 neurons
layer2 = Layer_Dense(n_inputs=5, n_neurons=2) ## Second layer with 5 inputs (from previous layer) and 2 neurons
## Forward pass through the layers
layer1.forward(X) ## Forward pass through first layer. We will now have layer1.output value
print("Layer 1 output = \n", layer1.output) ## Print output of first layer
layer2.forward(layer1.output) ## Forward pass through second layer. We will now have layer2.output value which is calculated from output of first layer
print("Layer 2 output = \n", layer2.output) ## Print output of second layer

Layer 1 output = 
 [[-0.25019707  0.29621499 -0.44316805  0.26722439 -0.07514709]
 [-0.0591695   0.61932802 -0.37870028  1.13393833 -0.65706718]
 [-0.19564971 -0.13415211 -0.14491714 -0.33268666 -0.06286878]]
Layer 2 output = 
 [[ 0.01619024  0.04631842]
 [-0.17965935  0.02002777]
 [ 0.04101197  0.05067731]]
